name: Rust CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Test
        run: cargo clippy -- -Dwarnings && cargo test

      - name: Build release
        run: cargo build --release

      - name: Build documentation
        run: cargo doc

      - name: Upload compiled files
        uses: actions/upload-artifact@v2
        with:
          name: rubble-rs-target
          path: 'target/**/*'

  deploy_doc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v2

      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: rubble-rs-target

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: 'target/doc'